import { Tutor } from "@/shared/types/tutor";

export const FEATURED_TUTORS: Tutor[] = [
  {
    id: 1,
    name: "Nguyễn Hương Giang",
    avatar: "https://i.pravatar.cc/150?u=giangnguyen",
    university: "ĐH Sư phạm Hà Nội",
    major: "Sư Phạm Tiếng Anh",
    rating: 5.0,
    reviewCount: 128,
    subjects: ["Tiếng Anh", "Luyện thi IELTS", "Giao tiếp"],
    bio: "Chào bạn! Mình là Hương Giang, hiện đang là giảng viên tại ĐH Sư phạm. Với 5 năm kinh nghiệm luyện thi IELTS, mình cam kết giúp bạn đạt target 7.0+ trong thời gian ngắn nhất.",
    price: 250000,
    location: "Cầu Giấy, Hà Nội",
    responseTime: "Phản hồi trong 15p",
    isTopRated: true,
    format: ["Online", "Trực tiếp"],
    levels: ["Lớp 10 - 12", "Đại học", "Người đi làm"],
  },
  {
    id: 2,
    name: "Trần Tuấn Dũng",
    avatar: "https://i.pravatar.cc/150?u=dungtran",
    university: "ĐH Bách Khoa Hà Nội",
    major: "Kỹ thuật Điều khiển & Tự động hóa",
    rating: 4.9,
    reviewCount: 95,
    subjects: ["Toán học", "Vật lý", "Khoa học"],
    bio: "Mình có thế mạnh về tư duy logic và giải quyết các bài toán khó. Phương pháp dạy của mình tập trung vào bản chất vấn đề thay vì học vẹt.",
    price: 200000,
    location: "Hai Bà Trưng, Hà Nội",
    responseTime: "Phản hồi trong 1h",
    isTopRated: true,
    format: ["Online", "Trực tiếp"],
    levels: ["Lớp 6 - 9", "Lớp 10 - 12", "Ôn thi ĐH"],
  },
  {
    id: 3,
    name: "Lê Minh Thùy",
    avatar: "https://i.pravatar.cc/150?u=thuyle",
    university: "ĐH Ngoại Ngữ - ĐHQGHN",
    major: "Ngôn ngữ Trung Quốc",
    rating: 4.8,
    reviewCount: 76,
    subjects: ["Tiếng Trung", "Luyện thi HSK"],
    bio: "Tiếng Trung không hề khó nếu bạn biết cách tiếp cận đúng. Mình sẽ hướng dẫn bạn từ cơ bản đến nâng cao một cách bài bản nhất.",
    price: 180000,
    location: "Đống Đa, Hà Nội",
    responseTime: "Phản hồi trong 30p",
    format: ["Online"],
    levels: ["Mọi lứa tuổi"],
  },
  {
    id: 4,
    name: "Phạm Quốc Bảo",
    avatar: "https://i.pravatar.cc/150?u=baopham",
    university: "ĐH Y Dược TP.HCM",
    major: "Y đa khoa",
    rating: 5.0,
    reviewCount: 112,
    subjects: ["Hóa học", "Sinh học"],
    bio: "Hỗ trợ học sinh nắm vững kiến thức nền tảng và phương pháp ôn thi khối B hiệu quả. Thủ khoa đầu vào ĐH Y Dược năm 2020.",
    price: 300000,
    location: "Quận 1, TP.HCM",
    responseTime: "Phản hồi trong 2h",
    isTopRated: true,
    format: ["Trực tiếp"],
    levels: ["Lớp 10 - 12", "Ôn thi ĐH"],
  },
  {
    id: 5,
    name: "Đặng Thị Mai",
    avatar: "https://i.pravatar.cc/150?u=maidang",
    university: "Học viện Tài chính",
    major: "Kế toán - Kiểm toán",
    rating: 4.9,
    reviewCount: 64,
    subjects: ["Toán học", "Tiếng Việt", "Luyện viết chữ đẹp"],
    bio: "Yêu trẻ và có phương pháp sư phạm phù hợp với học sinh tiểu học. Giúp bé yêu thích việc học ngay từ những ngày đầu.",
    price: 150000,
    location: "Thanh Xuân, Hà Nội",
    responseTime: "Phản hồi trong 1h",
    format: ["Online", "Trực tiếp"],
    levels: ["Lớp 1 - 5"],
  },
  {
    id: 6,
    name: "Nguyễn Gia Khánh",
    avatar: "https://i.pravatar.cc/150?u=giakhanh",
    university: "ĐH Kinh tế Quốc dân",
    major: "Kinh doanh quốc tế",
    rating: 4.7,
    reviewCount: 42,
    subjects: ["Toán học", "Tiếng Anh"],
    bio: "Hỗ trợ học sinh lớp 1-9 nắm vững kiến thức cơ bản và nâng cao. Phương pháp giảng dạy nhiệt tình, dễ hiểu.",
    price: 150000,
    location: "Hoàn Kiếm, Hà Nội",
    responseTime: "Phản hồi trong 1h",
    format: ["Online"],
    levels: ["Lớp 1 - 9"],
  },
  {
    id: 7,
    name: "Lê Duy Khánh",
    avatar: "https://i.pravatar.cc/150?u=duykhanh",
    university: "ĐH Khoa học Tự nhiên",
    major: "Toán học",
    rating: 4.9,
    reviewCount: 56,
    subjects: ["Toán học", "Luyện thi vào 10"],
    bio: "Chuyên luyện thi vào lớp 10 các trường chuyên. Giúp học sinh lấy lại gốc và bứt phá điểm số trong thời gian ngắn.",
    price: 220000,
    location: "Ba Đình, Hà Nội",
    responseTime: "Phản hồi trong 30p",
    format: ["Trực tiếp"],
    levels: ["Lớp 9", "Ôn thi vào 10"],
  },
];
